# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{socrates}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["wilkie"]
  s.date = %q{2011-01-29}
  s.description = %q{Be able to sparsely describe a course and generate a static website to present the course materials with a variety of themes}
  s.email = %q{wilkie05@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/socrates.rb",
    "lib/socrates/controllers/site_controller.rb",
    "lib/socrates/models/assignments.rb",
    "lib/socrates/models/information.rb",
    "lib/socrates/models/schedule.rb",
    "spec/information_spec.rb",
    "spec/schedule_spec.rb",
    "spec/site_controller_spec.rb",
    "test/information/multiple_teacher.yml",
    "test/information/multiple_teachers.yml",
    "test/information/normal.yml",
    "test/information/single_day.yml",
    "test/information/single_teacher.yml",
    "test/information/single_teachers.yml",
    "test/schedule/normal.yml"
  ]
  s.homepage = %q{http://github.com/wilkie/socrates}
  s.licenses = ["CC0"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Creates static sites for educational courses}
  s.test_files = [
    "spec/information_spec.rb",
    "spec/schedule_spec.rb",
    "spec/site_controller_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tilt>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<tilt>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<tilt>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

